name = "upload-worker"
main = "workers/upload-worker.ts"
compatibility_date = "2024-01-01"

# Development environment (includes local and staging)
[vars]
ALLOWED_ORIGINS = "http://localhost:3000,https://develop.cocktail-cult.pages.dev"

# R2 bucket configuration for development
[[r2_buckets]]
binding = "BUCKET"
bucket_name = "cocktail-compass-staging"
preview_bucket_name = "cocktail-compass-staging"

# Production environment
[env.production]
vars = { ALLOWED_ORIGINS = "https://cocktail-cult.pages.dev" }

[[env.production.r2_buckets]]
binding = "BUCKET"
bucket_name = "cocktail-compass-production"
preview_bucket_name = "cocktail-compass-production"

# Required secrets (to be set using wrangler secret put)
# - SUPABASE_URL
# - SUPABASE_SERVICE_ROLE_KEY